modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "eca"
version = "${mod_version}"
displayName = "Epic Core API"
displayURL = "https://modrinth.com/mod/epic-core-api"
logoFile = "logo.png"
authors = "CJiangqiu"
credits = '''
Contributor:WZZ,Mascot:MCreator
'''
description = '''
A library mod that provides powerful entity manipulation APIs through CoreMod (ITransformationService), Java Agent, and Mixin technologies.
'''

[[dependencies.eca]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eca]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "eca.mixins.json"
